/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as CoupRouteImport } from './routes/coup'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as TrouRouteImport } from './routes/trou'
import { Route as ApiCaddieRouteImport } from './routes/api/caddie'
import { Route as ApiSpeechRouteImport } from './routes/api/speech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const CoupRoute = CoupRouteImport.update({
  id: '/coup',
  path: '/coup',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const TrouRoute = TrouRouteImport.update({
  id: '/trou',
  path: '/trou',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaddieRoute = ApiCaddieRouteImport.update({
  id: '/api/caddie',
  path: '/api/caddie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeechRoute = ApiSpeechRouteImport.update({
  id: '/api/speech',
  path: '/api/speech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/coup': typeof CoupRoute
  '/menu': typeof MenuRoute
  '/parcours': typeof ParcoursRoute
  '/score': typeof ScoreRoute
  '/trou': typeof TrouRoute
  '/api/caddie': typeof ApiCaddieRoute
  '/api/speech': typeof ApiSpeechRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/coup': typeof CoupRoute
  '/menu': typeof MenuRoute
  '/parcours': typeof ParcoursRoute
  '/score': typeof ScoreRoute
  '/trou': typeof TrouRoute
  '/api/caddie': typeof ApiCaddieRoute
  '/api/speech': typeof ApiSpeechRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/coup': typeof CoupRoute
  '/menu': typeof MenuRoute
  '/parcours': typeof ParcoursRoute
  '/score': typeof ScoreRoute
  '/trou': typeof TrouRoute
  '/api/caddie': typeof ApiCaddieRoute
  '/api/speech': typeof ApiSpeechRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenue'
    | '/coup'
    | '/menu'
    | '/parcours'
    | '/score'
    | '/trou'
    | '/api/caddie'
    | '/api/speech'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenue'
    | '/coup'
    | '/menu'
    | '/parcours'
    | '/score'
    | '/trou'
    | '/api/caddie'
    | '/api/speech'
  id:
    | '__root__'
    | '/'
    | '/bienvenue'
    | '/coup'
    | '/menu'
    | '/parcours'
    | '/score'
    | '/trou'
    | '/api/caddie'
    | '/api/speech'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienvenueRoute: typeof BienvenueRoute
  CoupRoute: typeof CoupRoute
  MenuRoute: typeof MenuRoute
  ParcoursRoute: typeof ParcoursRoute
  ScoreRoute: typeof ScoreRoute
  TrouRoute: typeof TrouRoute
  ApiCaddieRoute: typeof ApiCaddieRoute
  ApiSpeechRoute: typeof ApiSpeechRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coup': {
      id: '/coup'
      path: '/coup'
      fullPath: '/coup'
      preLoaderRoute: typeof CoupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trou': {
      id: '/trou'
      path: '/trou'
      fullPath: '/trou'
      preLoaderRoute: typeof TrouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/caddie': {
      id: '/api/caddie'
      path: '/api/caddie'
      fullPath: '/api/caddie'
      preLoaderRoute: typeof ApiCaddieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speech': {
      id: '/api/speech'
      path: '/api/speech'
      fullPath: '/api/speech'
      preLoaderRoute: typeof ApiSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienvenueRoute: BienvenueRoute,
  CoupRoute: CoupRoute,
  MenuRoute: MenuRoute,
  ParcoursRoute: ParcoursRoute,
  ScoreRoute: ScoreRoute,
  TrouRoute: TrouRoute,
  ApiCaddieRoute: ApiCaddieRoute,
  ApiSpeechRoute: ApiSpeechRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
